//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.travleapply {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbltravleapply_ID;
	protected global::System.Web.UI.WebControls.Label lbltravle_ID;
		protected global::System.Web.UI.WebControls.TextBox txtapplyer_ID;
		protected global::System.Web.UI.WebControls.TextBox txtapply_time;
		protected global::System.Web.UI.WebControls.TextBox txtapply_state;
		protected global::System.Web.UI.WebControls.TextBox txtapply_msg;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
