//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.credit {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblcredit_id;
	protected global::System.Web.UI.WebControls.Label lbluser_telphone;
		protected global::System.Web.UI.WebControls.TextBox txtcredit_change;
		protected global::System.Web.UI.WebControls.TextBox txtcreditchange_type;
		protected global::System.Web.UI.WebControls.TextBox txtcreditchange_time;
		protected global::System.Web.UI.WebControls.TextBox txtcredit_balance;
		protected global::System.Web.UI.WebControls.TextBox txtcreditchange_comment;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
