//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.carInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblcar_id;
	protected global::System.Web.UI.WebControls.Label lbluser_telphone;
	protected global::System.Web.UI.WebControls.Label lblcar_level;
	protected global::System.Web.UI.WebControls.Label lblcar_brand;
	protected global::System.Web.UI.WebControls.Label lblcar_type;
	protected global::System.Web.UI.WebControls.Label lblcar_photo1;
	protected global::System.Web.UI.WebControls.Label lblcar_photo2;
	protected global::System.Web.UI.WebControls.Label lblcar_photo3;
	protected global::System.Web.UI.WebControls.Label lblcar_photo1_state;
	protected global::System.Web.UI.WebControls.Label lblcar_photo2_state;
	protected global::System.Web.UI.WebControls.Label lblcar_photo3_state;


       
    }
}
