//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.virtualgoods {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_ID;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_name;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_price;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_comment;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_pic_url;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_type;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_fun;


       
    }
}
