//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.travel {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txttravle_ID;
		protected global::System.Web.UI.WebControls.TextBox txtpromoter_userid;
		protected global::System.Web.UI.WebControls.TextBox txtrelease_time;
		protected global::System.Web.UI.WebControls.TextBox txtDestination;
		protected global::System.Web.UI.WebControls.TextBox txtstartplace;
		protected global::System.Web.UI.WebControls.TextBox txtreturn_time;
		protected global::System.Web.UI.WebControls.TextBox txtstart_time;
		protected global::System.Web.UI.WebControls.TextBox txttransportation;
		protected global::System.Web.UI.WebControls.TextBox txtfee;
		protected global::System.Web.UI.WebControls.TextBox txttravle_theme;
		protected global::System.Web.UI.WebControls.TextBox txttravle_personcount;
		protected global::System.Web.UI.WebControls.TextBox txtcompanion_condition;
		protected global::System.Web.UI.WebControls.TextBox txttravle_msg;
		protected global::System.Web.UI.WebControls.TextBox txtpic1;
		protected global::System.Web.UI.WebControls.TextBox txtpic2;
		protected global::System.Web.UI.WebControls.TextBox txtpic3;
		protected global::System.Web.UI.WebControls.TextBox txtincome_condition;
		protected global::System.Web.UI.WebControls.TextBox txtcar_condition;
		protected global::System.Web.UI.WebControls.TextBox txtheight_condition;
		protected global::System.Web.UI.WebControls.TextBox txtcredit_condition;
		protected global::System.Web.UI.WebControls.TextBox txtwantget_gift;
		protected global::System.Web.UI.WebControls.TextBox txtwantsend_gift;
		protected global::System.Web.UI.WebControls.TextBox txtreg_fee;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
