//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.travel {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbltravle_ID;
	protected global::System.Web.UI.WebControls.Label lblpromoter_userid;
	protected global::System.Web.UI.WebControls.Label lblrelease_time;
	protected global::System.Web.UI.WebControls.Label lblDestination;
	protected global::System.Web.UI.WebControls.Label lblstartplace;
	protected global::System.Web.UI.WebControls.Label lblreturn_time;
	protected global::System.Web.UI.WebControls.Label lblstart_time;
	protected global::System.Web.UI.WebControls.Label lbltransportation;
	protected global::System.Web.UI.WebControls.Label lblfee;
	protected global::System.Web.UI.WebControls.Label lbltravle_theme;
	protected global::System.Web.UI.WebControls.Label lbltravle_personcount;
	protected global::System.Web.UI.WebControls.Label lblcompanion_condition;
	protected global::System.Web.UI.WebControls.Label lbltravle_msg;
	protected global::System.Web.UI.WebControls.Label lblpic1;
	protected global::System.Web.UI.WebControls.Label lblpic2;
	protected global::System.Web.UI.WebControls.Label lblpic3;
	protected global::System.Web.UI.WebControls.Label lblincome_condition;
	protected global::System.Web.UI.WebControls.Label lblcar_condition;
	protected global::System.Web.UI.WebControls.Label lblheight_condition;
	protected global::System.Web.UI.WebControls.Label lblcredit_condition;
	protected global::System.Web.UI.WebControls.Label lblwantget_gift;
	protected global::System.Web.UI.WebControls.Label lblwantsend_gift;
	protected global::System.Web.UI.WebControls.Label lblreg_fee;


       
    }
}
