//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.user_tb {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuser_telphone;
		protected global::System.Web.UI.WebControls.CheckBox chkuser_sex;
		protected global::System.Web.UI.WebControls.TextBox txtuser_nikeName;
		protected global::System.Web.UI.WebControls.TextBox txtuser_photo;
		protected global::System.Web.UI.WebControls.TextBox txtuser_birthday;
		protected global::System.Web.UI.WebControls.TextBox txtuser_height;
		protected global::System.Web.UI.WebControls.TextBox txtuser_weight;
		protected global::System.Web.UI.WebControls.TextBox txtuser_address;
		protected global::System.Web.UI.WebControls.TextBox txtuser_job;
		protected global::System.Web.UI.WebControls.TextBox txtuser_income;
		protected global::System.Web.UI.WebControls.TextBox txtuser_pwd;
		protected global::System.Web.UI.WebControls.TextBox txtuser_marrystate;
		protected global::System.Web.UI.WebControls.TextBox txtuser_edu;
		protected global::System.Web.UI.WebControls.TextBox txtpersoncenter_bg;
		protected global::System.Web.UI.WebControls.TextBox txtuser_photo_state;
		protected global::System.Web.UI.WebControls.TextBox txtuser_state;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
