//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.user_tb {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluser_telphone;
	protected global::System.Web.UI.WebControls.Label lbluser_sex;
	protected global::System.Web.UI.WebControls.Label lbluser_nikeName;
	protected global::System.Web.UI.WebControls.Label lbluser_photo;
	protected global::System.Web.UI.WebControls.Label lbluser_birthday;
	protected global::System.Web.UI.WebControls.Label lbluser_height;
	protected global::System.Web.UI.WebControls.Label lbluser_weight;
	protected global::System.Web.UI.WebControls.Label lbluser_address;
	protected global::System.Web.UI.WebControls.Label lbluser_job;
	protected global::System.Web.UI.WebControls.Label lbluser_income;
	protected global::System.Web.UI.WebControls.Label lbluser_pwd;
	protected global::System.Web.UI.WebControls.Label lbluser_marrystate;
	protected global::System.Web.UI.WebControls.Label lbluser_edu;
	protected global::System.Web.UI.WebControls.Label lblpersoncenter_bg;
	protected global::System.Web.UI.WebControls.Label lbluser_photo_state;
	protected global::System.Web.UI.WebControls.Label lbluser_state;


       
    }
}
