//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.talent {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txttalent_ID;
		protected global::System.Web.UI.WebControls.TextBox txtuser_telphone;
		protected global::System.Web.UI.WebControls.TextBox txttalent_change_value;
		protected global::System.Web.UI.WebControls.TextBox txttalent_change_comment;
		protected global::System.Web.UI.WebControls.TextBox txttalent_change_time;
		protected global::System.Web.UI.WebControls.TextBox txttalent_change_type;
		protected global::System.Web.UI.WebControls.TextBox txttalent_result;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
