//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.sendgift {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsendgift_ID;
		protected global::System.Web.UI.WebControls.TextBox txtvirtualgoods_ID;
		protected global::System.Web.UI.WebControls.TextBox txtsender_id;
		protected global::System.Web.UI.WebControls.TextBox txtaccepter_id;
		protected global::System.Web.UI.WebControls.TextBox txtsend_time;
		protected global::System.Web.UI.WebControls.TextBox txtsendgift_comment;
		protected global::System.Web.UI.WebControls.TextBox txtsendgift_msg;
		protected global::System.Web.UI.WebControls.TextBox txtsendgift_count;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
