//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.sendgift {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblsendgift_ID;
	protected global::System.Web.UI.WebControls.Label lblvirtualgoods_ID;
	protected global::System.Web.UI.WebControls.Label lblsender_id;
	protected global::System.Web.UI.WebControls.Label lblaccepter_id;
	protected global::System.Web.UI.WebControls.Label lblsend_time;
	protected global::System.Web.UI.WebControls.Label lblsendgift_comment;
	protected global::System.Web.UI.WebControls.Label lblsendgift_msg;
	protected global::System.Web.UI.WebControls.Label lblsendgift_count;


       
    }
}
