//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.sms {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblsms_id;
	protected global::System.Web.UI.WebControls.Label lbluser_telphone;
		protected global::System.Web.UI.WebControls.TextBox txtsms_content;
		protected global::System.Web.UI.WebControls.TextBox txtsms_time;
		protected global::System.Web.UI.WebControls.TextBox txtsms_comment;
		protected global::System.Web.UI.WebControls.CheckBox chksms_ispay;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
