//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.chat_message {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblchat_ID;
	protected global::System.Web.UI.WebControls.Label lblchat_FROM;
	protected global::System.Web.UI.WebControls.Label lblchat_TO;
	protected global::System.Web.UI.WebControls.Label lblchat_content;
	protected global::System.Web.UI.WebControls.Label lblchat_time;
	protected global::System.Web.UI.WebControls.Label lblchat_comment;
	protected global::System.Web.UI.WebControls.Label lblchat_state;


       
    }
}
