//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.log {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtlog_id;
		protected global::System.Web.UI.WebControls.TextBox txtuser_telphone;
		protected global::System.Web.UI.WebControls.TextBox txtlog_ip;
		protected global::System.Web.UI.WebControls.TextBox txtlog_time;
		protected global::System.Web.UI.WebControls.TextBox txtLAT;
		protected global::System.Web.UI.WebControls.TextBox txtLNG;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
