//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace la.Web.log {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbllog_id;
	protected global::System.Web.UI.WebControls.Label lbluser_telphone;
	protected global::System.Web.UI.WebControls.Label lbllog_ip;
	protected global::System.Web.UI.WebControls.Label lbllog_time;
	protected global::System.Web.UI.WebControls.Label lblLAT;
	protected global::System.Web.UI.WebControls.Label lblLNG;


       
    }
}
